config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/create"
  get "sessions/destroy"

  resources :users

  resources :payment_types

  resources :orders

  resources :line_items

  resources :carts

  resources :products do
    get :who_bought, on: :member
  end

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store', via: :all
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy

	def add_product(product_id)
		current_item=line_items.find_by(product_id: product_id)
		if current_item
			current_item.quantity+=1
		else
			current_item=line_items.build(product_id: product_id)
			current_item.price=current_item.product.price
		end
		current_item
	end

	def remove_item(product_id)
		current_item=line_items.find_by(product_id: product_id)
		if current_item
			if current_item.quantity>1
				current_item.quantity-=1
				current_item.save!
				return true
			else
				current_item.destroy
				return true
			end
		end
		false
			# current_item
	end

	def total_price
		line_items.to_a.sum {|item| item.total_price}
	end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :order
	belongs_to :product
	belongs_to :cart

	def total_price
  		price * quantity
	end
end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :line_items, dependent: :destroy

	# PAYMENT_TYPES= %w(Check Credit-card Purchase-order)
	PAYMENT_TYPES=PaymentType.pluck(:name)

	validates :name, :address, :email, presence: true
	validates :pay_type, inclusion: PAYMENT_TYPES

	def add_line_items_from_cart(cart)
	    cart.line_items.each do |item|
	      item.cart_id = nil
	      line_items << item
	    end
	end
end

app/models/payment_type.rb
class PaymentType < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :line_items
	has_many :orders, through: :line_items
	before_destroy :ensure_not_referenced_by_any_line_item

	validates :title, :description, :image_url, presence: true		#validates for presence
	validates :price, numericality: {greater_than_or_equal_to: 0.01}	#validates that price is greater than 0.01
	validates :title, uniqueness: true
	validates_length_of :title, minimum: 10, message: 'must be 10+ characters'
	validates :image_url, allow_blank: true, format:{
		with: %r{\.(gif|jpg|jpeg|png)\Z}i,
		message: 'must be a url for .gif, .jpg, .jpeg, or .png'
	}

	def self.latest
		Product.order(:updated_at).last
	end

	def ensure_not_referenced_by_any_line_item
		if line_items.empty?
			true
		else
			errors.add(:base,'Line Items present')
			false
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true
  	has_secure_password
  	after_destroy :ensure_an_admin_remains

  	private
  		def ensure_an_admin_remains
  			if User.count.zero?
  				raise "Can't delete last user"
  			end
  		end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  	@total_orders=Order.count
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authorize, only: [:create,:update,:destroy]
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id==session[:cart_id]
    session[:cart_id]=nil
    respond_to do |format|
      format.html { redirect_to store_url }
      format.js
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url, notice: "Invalid cart"
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
	include CurrentCart
  skip_before_action :authorize
	before_action :set_cart
  def index
    if params[:set_locale]
      redirect_to store_url(locale: params[:set_locale])
    else
    	@products=Product.order(:title).where("locale = '#{I18n.locale}'")
    	@visits=track_visits
    end
  end

  def track_visits
  	session[:visits]||=0
  	session[:visits]+=1
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: "User #{@user.name} was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    user_updating=User.find(session[:user_id])
    respond_to do |format|
      if user_updating.authenticate(params[:user][:current_password]) and @user.update(user_params)
        format.html { redirect_to users_url, notice: "User #{@user.name} was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        flash[:notice]='Current password incorrect'
        format.html { render :edit}
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    begin
      @user.destroy
      flash[:notice]="User #{@user.name} deleted"
    rescue StandardError => e 
      flash[:notice]=e.message
    end
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def hidden_div_if(condition,attributes={},&block)
		if condition
			attributes["style"]="display:none"
		end
		content_tag("div",attributes,&block)
	end

	def us_to_euro(amt)
		if I18n.locale.to_s=='eu'
			return amt*0.93
		else
			amt
		end
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payment_types_helper.rb
module PaymentTypesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Welcome</h1> 

It's <%= Time.now %>
We have <%= pluralize(@total_orders, "order") %>.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title><%= t('.title') %></title>

  <%= stylesheet_link_tag    "application", media: "all",
    "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body class="<%= controller.controller_name %>">

  <div id="banner">

    <%= form_tag store_path, class: 'locale' do %>
      <%= select_tag 'set_locale', 
        options_for_select(LANGUAGES, I18n.locale.to_s),
        onchange: 'this.form.submit()' %>
      <%= submit_tag 'submit' %>
      <%= javascript_tag "$('.locale input').hide()" %>
    <% end %>
    
    <%= image_tag("logo.png") %>
    <%= @page_title || t('.title') %>
  </div>
  
  <div id="columns">
    <div id="side">
      <div id="cart">
      <% if @cart %>
        <%= hidden_div_if(@cart.line_items.empty?,id:'cadrt') do %>
          <%= render @cart %>
        <% end %>
      <% end %>
    </div>
      

      <ul>
        <li><a href="http://www...."><%= t('.home') %></a></li>
        <li><a href="http://www..../faq"><%= t('.questions') %></a></li>
        <li><a href="http://www..../news"><%= t('.news') %></a></li>
        <li><a href="http://www..../contact"><%= t('.contact') %></a></li>
      </ul>
      <% if session[:user_id] %>
        <ul>
          <li><%= link_to 'Orders',   orders_path   %></li>
          <li><%= link_to 'Products', products_path %></li>
          <li><%= link_to 'Users',    users_path    %></li>
        </ul>
        <%= button_to 'Logout', logout_path, method: :delete   %>
      <% end %>
      <p id='time'></p>
    </div>
    <div id="main">

      <%= yield %>

    </div>
  </div>

</body>
</html>

app/views/order_notifier/received.html.erb
<h1>OrderNotifier#received</h1>

<p>
  <%= @greeting %>, find me in app/views/order_notifier/received.html.erb
</p>

app/views/order_notifier/received.text.erb
Hello <%= @order.name %>

Thank you for your business, we recieved the following order:

<%= render @order.line_items %>

Expect another email when the order ships.

-Depot

app/views/order_notifier/shipped.html.erb
<h3>Pragmatic Order Shipped</h3>
<p>
  This is just to let you know that we've shipped your recent order:
</p>

<table>
  <tr><th colspan="2">Qty</th><th>Description</th></tr>
<%= render @order.line_items -%>
</table>

app/views/order_notifier/shipped.text.erb
OrderNotifier#shipped

<%= @greeting %>, find me in app/views/order_notifier/shipped.text.erb